spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sys?characterEncoding=UTF-8
    #命令行进入mysql mysql -u "账号" -p
    #show character set；                    查看mysql支持的字符集
    #show variable like ‘character_set%’；   查看数据库编码
    #show variables like ‘character%’；      查看当前mysql使用的字符集
    #show variables like ‘collation%’;       查看当前数据库的校队规则
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: sister
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080

